name: Java CI with Checkstyle

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Descarga el código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Instalar dependencias y compilar
      - name: Install dependencies
        run: mvn install

      # Ejecutar Checkstyle
      - name: Run Checkstyle
        run: mvn checkstyle:check

      # Ejecutar tests
      - name: Run tests
        run: mvn test
